###
GET http://10.0.0.1:3333/test

###
GET http://10.0.0.1:3333/tickets/getTicket/8E494C66

###
GET http://10.0.0.1:3333/tickets/getAllTickets/

###
GET http://10.0.0.1:3333/tv/getTv?model=topRatedTv&page=1

###
GET http://10.0.0.1:3333/tickets/validate-ticket/F70BFBF8

###
GET http://10.0.0.1:3333/nextShow/showSchedule